# Generated by Django 2.2.6 on 2019-10-13 12:32
# noqa

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20191007_2133")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
