# Generated by Django 2.2.6 on 2019-10-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auto_20191013_1232"),
        ("users", "0003_auto_20191013_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.Organization",
            ),
        )
    ]
