# Generated by Django 3.0.2 on 2020-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='domain',
            field=models.URLField(),
        ),
    ]
