# Generated by Django 3.0.2 on 2020-02-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aws_environments', '0003_auto_20200205_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('changes_pending', 'Pending changes'), ('ready', 'Ready'), ('error', 'Failed to apply changes')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='aws_environments.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='environment',
            name='last_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env', to='aws_environments.EnvStatus'),
        ),
    ]
