# Generated by Django 3.0.2 on 2020-02-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0006_auto_20200213_1425"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project", unique_together={("environment_id", "name")},
        ),
    ]
