# Generated by Django 3.0.2 on 2020-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0009_auto_20200219_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="alb_port_http",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="alb_port_https",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="container_port",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="health_check_endpoint",
            field=models.CharField(default="/", max_length=150),
        ),
    ]
