# Generated by Django 3.0.2 on 2020-02-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0012_auto_20200223_1637"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildWorker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=20, null=True, unique=True)),
                ("launched_at", models.DateTimeField(null=True)),
                ("instance_id", models.CharField(max_length=80, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_workers",
                        to="aws_environments.Service",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
