# Generated by Django 3.0.2 on 2020-02-26 20:30

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0013_buildworker"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildworker",
            name="public_ip",
            field=fernet_fields.fields.EncryptedTextField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buildworker",
            name="ssh_key_name",
            field=fernet_fields.fields.EncryptedTextField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
