# Generated by Django 3.0.2 on 2020-02-26 21:49

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0014_auto_20200226_2030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildworker",
            name="public_ip",
            field=fernet_fields.fields.EncryptedTextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="component",
            field=models.CharField(
                choices=[
                    ("service", "Service"),
                    ("project", "Project"),
                    ("environment", "Environment"),
                    ("build_worker", "Build Worker"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
