# Generated by Django 3.0.2 on 2020-02-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("aws_environments", "0015_auto_20200226_2149"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildworker",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_builders",
                to="organizations.Organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="organizations.Organization",
            ),
            preserve_default=False,
        ),
    ]
