# Generated by Django 3.0.2 on 2020-03-02 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('aws_environments', '0017_auto_20200301_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='component',
            field=models.CharField(choices=[('service', 'Service'), ('project', 'Project'), ('environment', 'Environment'), ('build_worker', 'Build Worker'), ('deployment', 'Deployment')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, null=True, unique=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=20)),
                ('is_success', models.NullBooleanField()),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_deployments', to='organizations.Organization')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='aws_environments.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
