# Generated by Django 3.0.2 on 2020-03-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws_environments', '0022_auto_20200322_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='aws_environments.Project'),
        ),
    ]
