# Generated by Django 3.0.2 on 2020-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_environments', '0025_auto_20200324_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='identifier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
