# Generated by Django 3.0.2 on 2020-04-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0027_auto_20200423_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="engine",
            field=models.CharField(
                choices=[("postgres", "Postgres"), ("redis", "Redis"), ("s3", "S3")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="kind",
            field=models.CharField(
                choices=[("database", "Db"), ("cache", "Cache"), ("bucket", "Bucket")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="preset",
            field=models.CharField(
                choices=[("dev", "Dev"), ("prod", "Prod"), ("statics", "Statics")],
                max_length=50,
            ),
        ),
    ]
