# Generated by Django 3.0.5 on 2020-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0029_auto_20200430_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="default_dockerfile_target",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="default_dockerfile_path",
            field=models.CharField(default="Dockerfile", max_length=100),
        ),
    ]
