# Generated by Django 3.0.5 on 2020-05-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aws_environments", "0030_auto_20200503_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildworker",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builders",
                to="aws_environments.Project",
            ),
        ),
    ]
