# Generated by Django 3.1.2 on 2020-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_environments', '0032_auto_20200504_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='is_success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='servicedeployment',
            name='is_success',
            field=models.BooleanField(null=True),
        ),
    ]
